### ISSUE TITLE
New version of Discordgo broke something 

### ISSUE THREAD

**Issue by ZaneSylva** [noah427/Clypeus#29]
Was testing, nuked a model of a server with more than 100 channels, bot did not stop the nuke. Had proper perms and hoist. 

![image](https://user-images.githubusercontent.com/96715560/147514878-88be9a78-d2f0-4ca7-9341-430db84f63c2.png)

After nuke, suspicion level only raised to 25
![image](https://user-images.githubusercontent.com/96715560/147514890-f4e8bc1b-ec07-4bbc-af07-3589cac6d434.png)

**Comment by noah427** [comment]
If anyone can reproduce this I will try to fix it but so far it's been working perfectly for me.

**Comment by noah427** [comment]
This error is caused by discord ratelimit us
